name: build mele-a200 image

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
     - name: install dep
       run: |
         sudo apt-get update
         sudo apt-get install -y curl jq gpg python3-pyquery wget xz-utils make gcc-arm-linux-gnueabihf flex bison dpkg-dev bc rsync kmod cpio libssl-dev git lsb vim libelf-dev neofetch python3-pip python3-tk debhelper zstd dpkg-sig mmdebstrap qemu-user-static usrmerge binfmt-support systemd-container
      

      - name: Checkout armbian/build
        run: |
          git clone --depth=1 --branch=main https://github.com/hy5528/Build-Armbian

      - name: Patch Mele A200
        run: |          
          cat <<EOF > ./Build-Armbian/config/boards/aml-s812.conf
          BOARD_NAME="S812"
          BOARDFAMILY="aml-s812"
          BOOTCONFIG="linux-aml-s812-current.config"
          KERNEL_TARGET="current,edge"
          EOF

      - name: Build for mele-a200
        run: |
          cd Build-Armbian
          sudo ./compile.sh build BOARD=aml-s812 BRANCH=current BUILD_MINIMAL=yes KERNEL_CONFIGURE=no RELEASE=jammy FORCE_CHECK_MD5_PACKAGES=no

      - uses: actions/upload-artifact@v4
        with:
          name: built-images
          path: build/output/images
