name: build aml-s812 bullseye image

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    container: ghcr.io/armbian/docker-armbian-build:armbian-ubuntu-jammy-latest
    

      - name: Checkout armbian/build
        run: |
          git clone --depth=1 --branch=main https://github.com/hy5528/build

      - name: Build for aml-s812
        run: |
          cd build
          ./compile.sh  BOARD=onecloud  BRANCH=current RELEASE=jammy  BUILD_MINIMAL=yes  BUILD_DESKTOP=no KERNEL_ONLY=no KERNEL_CONFIGURE=no COMPRESS_OUTPUTIMAGE=sha,gpg,img DOWNLOAD_MIRROR=china MAINLINE_MIRROR=tuna EXTRAWIFI=no
   
      - uses: actions/upload-artifact@v4
        with:
          name: built-images
          path: Build-Armbian/output/images/
