name: build OneCloud image

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Checkout armbian/build
        run: |
          git clone --depth=1 --branch=main https://github.com/hy5528/build
          
      - name: Patch onecloud
        run: |          
          cat <<EOF > ./build/config/boards/onecloud.conf
          BOARD_NAME="onecloud"
          BOARDFAMILY="sun5i"
          BOARD_MAINTAINER=""
          HAS_VIDEO_OUTPUT="yes"
          BOOTCONFIG="linux-meson-legacy.config"
          KERNEL_TARGET="current,legacy"
          EOF

      - name: Build for OneCloud
        run: |
          cd build
          ./compile.sh build BOARD=onecloud BRANCH=legacy BUILD_DESKTOP=no BUILD_MINIMAL=yes COMPRESS_OUTPUTIMAGE=img EXTRAWIFI=yes  KERNEL_CONFIGURE=no  DOWNLOAD_MIRROR=china MAINLINE_MIRROR=tuna RELEASE=jammy BOOTSIZE=64  SYNC_CLOCK=no INCLUDE_HOME_DIR=yes 
      - uses: actions/upload-artifact@v4
        with:
          name: built-images
          path: build/output/images
