
name: build s805 image

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    container: ghcr.io/armbian/docker-armbian-build:armbian-ubuntu-jammy-latest
    steps:
      - name: Checkout armbian/build
        run: |
          git clone --depth=1 --branch=main https://github.com/mofeng-git/build
      - name: Build for s805
        run: |
          cd build
          sudo ./compile.sh \
               BOARD=onecloud \
               BRANCH=current \
               RELEASE=jammy \
               BUILD_MINIMAL=yes \
               BUILD_DESKTOP=no \
               KERNEL_ONLY=no \
               KERNEL_CONFIGURE=no \
          
      - uses: actions/upload-artifact@v4
        with:
          name: built-images
          path: build/output/images

