name: build aml-s812 image

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Checkout armbian/build
        run: |
          git clone --depth=1 --branch=main https://github.com/hy5528/Build-Armbian

      - name: Patch aml-s812
        run: |          
          cat <<EOF > ./build/config/boards/aml-s812.conf
          BOARD_NAME="S812"
          BOARDFAMILY=aml-s812
          BOOTCONFIG="odroidc_config"
          BOARD_DIR=packages/bsp/aml-s812
          ADD_UBOOT="yes"
          KERNEL_TARGET="legacy,current,dev"
          FULL_DESKTOP="yes"
          EOF

      - name: Build for aml-s812
        run: |
          cd Build-Armbian
          ./compile.sh build BOARD=aml-s812 BRANCH=legacy BUILD_DESKTOP=no BUILD_MINIMAL=yes COMPRESS_OUTPUTIMAGE=img EXTRAWIFI=yes  KERNEL_CONFIGURE=no  DOWNLOAD_MIRROR=china MAINLINE_MIRROR=tuna RELEASE=jammy BOOTSIZE=64  SYNC_CLOCK=no INCLUDE_HOME_DIR=yes 

      - name: Build burn for aml-s812
        run: |
          cd Build-Armbian
          sudo ./userpatches/burnimg-pack.sh output/images/Armbian_24.03_Aml-s812_jammy_current_5.9.0-rc7_minimal.img

      - uses: actions/upload-artifact@v4
        with:
          name: built-images
          path: Build-Armbian/output/images/
