name: build aml-s812 image

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Checkout armbian/build
        run: |
          git clone --depth=1 --branch=main https://github.com/hy5528/Build-Armbian

      - name: Patch aml-s812
        run: |          
          cat <<EOF > ./Build-Armbian/config/boards/aml-s812.conf
          BOARD_NAME="S812"
          BOARDFAMILY=aml-s812
          BOOTCONFIG="linux-aml-s812-current.config"
          BOARD_DIR=packages/bsp/aml-s812
          ADD_UBOOT="yes"
          KERNEL_TARGET="legacy,current,dev"
          FULL_DESKTOP="yes"
          EOF

      - name: Build for aml-s812
        run: |
          cd Build-Armbian
          sudo ./compile.sh  BOARD=aml-s812 BRANCH=current RELEASE=jammy BUILD_MINIMAL=yes BUILD_DESKTOP=no KERNEL_ONLY=no KERNEL_CONFIGURE=no COMPRESS_OUTPUTIMAGE=sha,img EXTRAWIFI=yes DOWNLOAD_MIRROR=china MAINLINE_MIRROR=tun

      - name: Build burn for aml-s812
        run: |
          cd Build-Armbian
          sudo ./userpatches/burnimg-pack.sh output/images/Armbian_24.03_Aml-s812_jammy_current_5.9.0-rc7_minimal.img

      - uses: actions/upload-artifact@v4
        with:
          name: built-images
          path: Build-Armbian/output/images/
