name: build mele-a200 image

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Checkout armbian/build
        run: |
          git clone --depth=1 --branch=main https://github.com/hy5528/Build-Armbian

      - name: Patch Mele A200
        run: |          
          cat <<EOF > ./Build-Armbian/config/boards/mele-a200.conf
          BOARD_NAME="S812"
          BOARDFAMILY=aml-s812
          BOOTCONFIG="odroidc_config"
          BOARD_DIR=packages/bsp/aml-s812
          ADD_UBOOT="yes"
          KERNEL_TARGET="legacy,current,dev"
          FULL_DESKTOP="yes"
          EOF

      - name: Build for mele-a200
        run: |
          cd Build-Armbian
          ./compile.sh build BOARD=aml-s812 BRANCH=current BUILD_MINIMAL=yes KERNEL_CONFIGURE=no RELEASE=jammy FORCE_CHECK_MD5_PACKAGES=no

      - uses: actions/upload-artifact@v4
        with:
          name: built-images
          path: Build-Armbian/output/images
