name: build OneCloud image

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Checkout armbian/build
        run: |
          git clone --depth=1 --branch=main https://github.com/mofeng-git/build

      - name: Patch OneCloud
        run: |          
          cat <<EOF > ./build/config/boards/onecloud.conf
          BOARD_NAME="OneCloud"
          BOARDFAMILY="meson8b"
          BOARD_MAINTAINER="hzyitc"
          KERNELDIR='linux-aml-5.9'
          KERNELSOURCE='https://github.com/xdarklight/linux.git'
          KERNELBRANCH='branch:meson-mx-integration-5.9-20200930'
          KERNEL_DRIVERS_SKIP+=(driver_mt7921u_add_pids)
          KERNEL_DRIVERS_SKIP+=(driver_rtw88)
          KERNEL_DRIVERS_SKIP+=(driver_rtl8723cs)

          BOOTCONFIG="none"
          BOOTSCRIPT="boot-onecloud.cmd:boot.cmd"
          BOOTENV_FILE="onecloud.txt"

          OFFSET="16"
          BOOTSIZE="64"
          BOOTFS_TYPE="fat"
          EOF

      - name: Build for OneCloud
        run: |
          cd build
          ./compile.sh build BOARD=onecloud BRANCH=currentBUILD_DESKTOP=no BUILD_MINIMAL=yes COMPRESS_OUTPUTIMAGE=img EXTRAWIFI=yes  KERNEL_CONFIGURE=no  DOWNLOAD_MIRROR=china MAINLINE_MIRROR=tuna RELEASE=jammy BOOTSIZE=64  SYNC_CLOCK=no INCLUDE_HOME_DIR=yes 
      - uses: actions/upload-artifact@v4
        with:
          name: built-images
          path: build/output/images
