name: build mele-a200 image

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: install dep
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq gpg python3-pyquery wget xz-utils make gcc-arm-linux-gnueabihf flex bison dpkg-dev bc rsync kmod cpio libssl-dev git lsb vim libelf-dev neofetch python3-pip python3-tk debhelper zstd dpkg-sig mmdebstrap qemu-user-static usrmerge binfmt-support systemd-container
      

      - name: Checkout armbian/build
        run: |
          git clone --depth=1 --branch=main https://github.com/hy5528/Build-Armbian

      - name: Patch Mele A200
        run: |          
          cat <<EOF > ./Build-Armbian/config/boards/aml-s812.conf
          BOARD_DIR=packages/bsp/aml-s812
          ADD_UBOOT="yes"
          KERNEL_TARGET="legacy,current,dev"
          FULL_DESKTOP="yes"
          EOF

      - name: Build for mele-a200
        run: |
          cd Build-Armbian
          sudo ./compile.sh  BOARD=aml-s812 BRANCH=current RELEASE=jammy BUILD_MINIMAL=yes BUILD_DESKTOP=no KERNEL_ONLY=no KERNEL_CONFIGURE=no COMPRESS_OUTPUTIMAGE=sha,gpg,img DOWNLOAD_MIRROR=china MAINLINE_MIRROR=tuna EXTRAWIFI=no
      - name: Build burn for aml-s812
        run: |
          cd Build-Armbian
          sudo ./userpatches/burnimg-pack.sh output/images/Armbian_24.03_Aml-s812_jammy_current_5.9.0-rc7_minimal.img
      - uses: actions/upload-artifact@v4
        with:
          name: built-images
          path: build/output/images
