
name: build mele-a200 image

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:buster
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          # 这个值是保留给系统的空间大小，之前设置太小，总会在安装依赖或者编译过程中报设备空间不足的错误而导致编译失败
          root-reserve-mb: 18096
          swap-size-mb: 2266
          remove-dotnet: 'true'
          remove-android: 'true'

      - name: Checkout armbian/build
        run: |
          git clone --depth=1 --branch=master https://github.com/witallwang/Build-Armbian
      - name: Build for mele-a200
        run: |
          cd Build-Armbian
          sudo ./compile.sh build BOARD=aml-s812 BRANCH=legacy BUILD_DESKTOP=no BUILD_MINIMAL=yes COMPRESS_OUTPUTIMAGE=img EXTRAWIFI=yes  KERNEL_CONFIGURE=no  DOWNLOAD_MIRROR=china MAINLINE_MIRROR=tuna RELEASE=jammy BOOTSIZE=64  SYNC_CLOCK=no INCLUDE_HOME_DIR=yes  KERNEL_COMPILER=/home/mofeng/code/toolchain/gcc-arm-9.2-2019.12-x86_64-arm-none-linux-gnueabihf/bin/arm-none-linux-gnueabihf-

      - uses: actions/upload-artifact@v4
        with:
          name: built-images
          path: build/output/images

