
name: build mele-a200 image

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Checkout armbian/build
        run: |
          git  clone --depth=1 https://github.com/mofeng-git/Build-Armbian
      - name: Build for mele-a200
        run: |
          cd Build-Armbian
          ./compile.sh  BOARD=aml-s812 BRANCH=current RELEASE=jammy BUILD_MINIMAL=yes BUILD_DESKTOP=no KERNEL_ONLY=no KERNEL_CONFIGURE=no COMPRESS_OUTPUTIMAGE=sha,img EXTRAWIFI=yes DOWNLOAD_MIRROR=china MAINLINE_MIRROR=tun

      - uses: actions/upload-artifact@v4
        with:
          name: built-images
          path: build/output/images

